class Hindi {
  static const Map<String, String> values = {
    "login": "लॉगिन",
    "signup": "साइन अप",
    "logout": "लॉग आउट",
    "email": "ईमेल",
    "password": "पासवर्ड",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "forgotPassword": "पासवर्ड भूल गए?",
    "loginTitle": "अपने खाते में लॉगिन करें",
    "signupTitle": "नया खाता बनाएं",
    "welcome": "स्वागत है",
    "welcomeMessage": "ऐप में आपका स्वागत है",
    "continueWithGoogle": "Google से जारी रखें",
    "continueWithPhone": "फ़ोन नंबर से जारी रखें",

    "home": "होम",
    "dashboard": "डैशबोर्ड",
    "search": "खोजें",
    "seeAll": "सभी देखें",
    "explore": "खोजें",
    "trending": "प्रचलित",
    "recent": "हाल ही में",

    "profile": "प्रोफ़ाइल",
    "editProfile": "प्रोफ़ाइल संपादित करें",
    "name": "नाम",
    "phone": "फ़ोन",
    "location": "स्थान",
    "update": "अपडेट करें",

    "settings": "सेटिंग्स",
    "language": "भाषा",
    "theme": "थीम",
    "darkMode": "डार्क मोड",
    "lightMode": "लाइट मोड",
    "notifications": "सूचनाएं",
    "privacyPolicy": "गोपनीयता नीति",
    "termsConditions": "नियम और शर्तें",

    "ok": "ठीक है",
    "cancel": "रद्द करें",
    "yes": "हाँ",
    "no": "नहीं",
    "submit": "सबमिट करें",
    "next": "अगला",
    "back": "पिछला",
    "skip": "छोड़ें",
    "getStarted": "शुरू करें",

    "errorOccurred": "एक त्रुटि हुई",
    "success": "सफलता",
    "invalidEmail": "अमान्य ईमेल पता",
    "passwordMismatch": "पासवर्ड मेल नहीं खा रहे",
    "requiredField": "यह फ़ील्ड आवश्यक है",
    "loginSuccess": "लॉगिन सफल",
    "signupSuccess": "साइन अप सफल",
    "loading": "लोड हो रहा है...",
    "noData": "कोई डेटा नहीं मिला",

    "onboardingTitle1": "नई सुविधाएं खोजें",
    "onboardingTitle2": "तेज और सुरक्षित",
    "onboardingTitle3": "अपनी यात्रा शुरू करें",
    "onboardingDesc1": "ऐप की अद्भुत सुविधाओं का अन्वेषण करें।",
    "onboardingDesc2": "आपका डेटा हमारे साथ सुरक्षित है।",
    "onboardingDesc3": "चलिए शुरू करते हैं!",

    "selectLanguage": "भाषा चुनें",
    "english": "अंग्रेज़ी",
    "hindi": "हिन्दी",
    "gujarati": "गुजराती",

    "noNotifications": "कोई नई सूचना नहीं",
    "contactUs": "संपर्क करें",
    "aboutUs": "हमारे बारे में",
    "version": "ऐप संस्करण"
  };
}
